version: "3"

services:

  control-server:
    image: alinchis/docker-control-server
    volumes:
      - "~/Git/PATJ-Manager/patj-control-server:/root/PATJ-Manager/patj-control-server"
    working_dir: /root/PATJ-Manager/patj-control-server
    command: npm start
    depends_on:
      - "sql-server"
    ports:
      - "3333:3030"

  display-server:
    image: alinchis/docker-display-server
    volumes:
      - "~/Git/PATJ-Manager/patj-display-server:/root/PATJ-Manager/patj-display-server"
    working_dir: /root/PATJ-Manager/patj-display-server
    command: bash -c "npm rebuild node-sass && npm run serve"
    ports:
      - "8888:8080"
    depends_on:
      - "control-server"

  sql-server:
    image: alinchis/docker-sql-server
    restart: always
    volumes:
      - "~/Git/PATJ-Manager/patj-docker-data/PostgreSQL:/var/lib/postgresql"
    ports:
      - "5555:5432"
